### ISSUE TITLE
 npm run bench-all gives me a: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by ivanceras** [krausest/js-framework-benchmark#1024]
```
npm run bench-all
```
gives me this error
```log
FORKING:  01_run1k  BatchSize  12
<home>/js-framework-benchmark/webdriver-ts/node_modules/lighthouse/lighthouse-core/runner.js:70
      const axeVersion = artifacts.Accessibility?.version;
                                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (<home>/js-framework-benchmark/webdriver-ts/node_modules/lighthouse/lighthouse-core/index.js:8:16)
```

**Comment by krausest** [comment]
That's strange. Can you please post your `node --version` ?

**Comment by ivanceras** [comment]
Here is the version of the pre-requisites
```log
npm --version
7.22.0

node --version
v10.19.0

java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

javac -version
javac 11.0.14.1


Linux 5.13.0-39-generic
```

**Comment by krausest** [comment]
Thanks and sorry the README is outdated for the node.js version, I'll fix that soon.
Can you please update to node 16? The docker build currently uses 16.13.2, on OSX I use a 16.14.2, so the latest LTS node 16 release should do fine.

**Comment by ivanceras** [comment]
So, I tried issuing `npm install webpack-cli`, without the `-D` flag and it seem to install it successfully.

```shell
npm install webpack-cli

up to date, audited 521 packages in 1s

53 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

However running the `npm run results` produce a new set of errors:

```log
[webpack-cli] Failed to load '<home>/js-framework-benchmark/webdriver-ts-results/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'html-webpack-plugin'
```

Perhaps, there should be a script which would install the prerequisites.

**Comment by ivanceras** [comment]
Ah, I missed that step.

I think I see the results of `keyed/vanillajs` in the table now.

Thank you!

One last thing, Is there a way to run all the benchmark for all the frameworks without having to invoke the benchmark individually for each of the frameworks?

**Comment by krausest** [comment]
Great + yes, of course: Just run `npm run bench` in the main directory and `npm run results` when all benchmarks finished.

**Comment by krausest** [comment]
And just to make sure: To build all frameworks you can invoke `npm run build-prod` in the root dir.

**Comment by ivanceras** [comment]
I also seem to be getting an error of outdated version of chrome:

```shell
type: object  instance of Error true  Message:  session not created: This version of ChromeDriver only supports Chrome version 99
Current browser version is 86.0.4240.111 with binary path /usr/bin/google-chrome
```
I will have to update my chrome

**Comment by krausest** [comment]
Yes. Chromedriver got very picky about the supported chrome version and allows according to my experience only +- 1 versions.
