### ISSUE TITLE
literaljs doesn't build anymore

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1054]
The build for literaljs stopped to work:
```
root@7dd76bd53ac7:/build/frameworks/non-keyed/literaljs# npm run build-prod

> js-framework-benchmark-non-keyed-literaljs@1.0.0 build-prod
> cross-env NODE_ENV=production parcel build index.html --public-url /frameworks/non-keyed/literaljs/dist/

🚨  /build/frameworks/non-keyed/literaljs/index.js: Invalid Version: undefined
    at new SemVer (/build/frameworks/non-keyed/literaljs/node_modules/semver/semver.js:314:11)
    at compare (/build/frameworks/non-keyed/literaljs/node_modules/semver/semver.js:647:10)
    at lt (/build/frameworks/non-keyed/literaljs/node_modules/semver/semver.js:688:10)
    at /build/frameworks/non-keyed/literaljs/node_modules/@babel/preset-env/lib/index.js:275:22
    at Object.default (/build/frameworks/non-keyed/literaljs/node_modules/@babel/helper-plugin-utils/lib/index.js:23:12)
    at getEnvPlugins (/build/frameworks/non-keyed/literaljs/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/build/frameworks/non-keyed/literaljs/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/build/frameworks/non-keyed/literaljs/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/build/frameworks/non-keyed/literaljs/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/build/frameworks/non-keyed/literaljs/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)
```
I'm moving it to the broken-frameworks folder.

**Comment by krausest** [comment]
@Mikeysax Hi Michael, do you haven an idea why the build stopped to work?

**Comment by Mikeysax** [comment]
@krausest no idea, I haven't touched it. Seems like a dependency issue with semver or parcel, the bundler tool.

**Comment by krausest** [comment]
Thanks!
