### ISSUE TITLE
Update imba to build with node 18.15.0

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1209]
It should be possible to build all frameworks with the latest node LTS (currently 18.5.0). In this issue I'll collect all those frameworks where a simple update doesn't help.

I also want to remove the necessity to set `export NODE_OPTIONS=--openssl-legacy-provider` which means webpack must be updated.

**Comment by krausest** [comment]
keyed/imba doesn't build anymore, even with with the old version.
```
> js-framework-benchmark-imba@1.0.1 build-prod
> webpack

/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/loader-runner/lib/LoaderRunner.js:133
		if(isError) throw e;
		            ^

TypeError: Cannot read properties of null (reading 'loader')
    at Object.emitError (/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/webpack/lib/NormalModule.js:170:52)
    at module.exports (/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/imba/loader.js:118:8)
    at LOADER_EXECUTION (/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/stefan/js-framework-benchmark/frameworks/keyed/imba/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

Bumping versions with `ncu` results in
```
> js-framework-benchmark-imba@1.0.1 build-prod
> webpack

assets by status 1.92 KiB [cached] 1 asset
./src/main.imba 39 bytes [not cacheable] [built] [code generated] [1 error]

ERROR in ./src/main.imba
Module build failed (from ./node_modules/imba/loader.js):
Error: Cannot find module 'loader-utils'
```
@somebee @allain Can you take a look at it please?

**Comment by krausest** [comment]
I moved imba into the broken-frameworks folder.
