### ISSUE TITLE
Ember v2.10.0-beta.3 does not build

### ISSUE THREAD

**Issue by ericpts** [krausest/js-framework-benchmark#133]
``` bash
[ericpts:...chmark/ember-v2.10.0-beta.3]$ npm run build-prod                                                                                                                                             (master) 

> ember-temp@0.0.0 build-prod /tmp/js-framework-benchmark/ember-v2.10.0-beta.3
> ember build --environment=production

WARNING: Node v7.5.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
cleaning up...
Build failed.
File: assets/vendor.css
The Broccoli Plugin: [broccoli-persistent-filter:CleanCSSFilter] failed with:
Error: An error found while optimizing CSS with clean-css:
  * Ignoring local source map at "/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/tmp/broccoli_persistent_filterclean_cssfilter-input_base_path-L7AxF5Ym.tmp/assets/bootstrap.min.css.map" as resource is missing.

clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
    at minify (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css-promise/index.js:63:18)
    at /tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/clean.js:107:9
    at Object.callback (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/read-sources.js:29:9)
    at doApplySourceMaps (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/apply-source-maps.js:61:23)
    at /tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/apply-source-maps.js:86:12
    at extractInputSourceMapFrom (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/apply-source-maps.js:122:14)
    at fetchAndApplySourceMap (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/apply-source-maps.js:79:10)
    at doApplySourceMaps (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/apply-source-maps.js:57:14)
    at applySourceMaps (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/apply-source-maps.js:33:5)
    at Object.callback (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/clean-css/lib/reader/read-sources.js:26:12)

The broccoli plugin was instantiated at: 
    at CleanCSSFilter.Plugin (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/broccoli-plugin/index.js:7:31)
    at CleanCSSFilter.Filter [as constructor] (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/broccoli-persistent-filter/index.js:62:10)
    at CleanCSSFilter (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/broccoli-clean-css/index.js:29:5)
    at module.exports.preprocessMinifyCss (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/ember-cli-preprocess-registry/preprocessors.js:112:12)
    at EmberApp.styles (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/ember-cli/lib/broccoli/ember-app.js:1350:23)
    at EmberApp.toArray (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/ember-cli/lib/broccoli/ember-app.js:1647:10)
    at EmberApp.toTree (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/ember-cli/lib/broccoli/ember-app.js:1668:30)
    at module.exports (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/ember-cli-build.js:29:14)
    at Class.setupBroccoliBuilder (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/ember-cli/lib/models/builder.js:72:19)
    at Class.init (/tmp/js-framework-benchmark/ember-v2.10.0-beta.3/node_modules/ember-cli/lib/models/builder.js:52:10)



npm ERR! Linux 4.9.0-1-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-prod"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ember-temp@0.0.0 build-prod: `ember build --environment=production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ember-temp@0.0.0 build-prod script 'ember build --environment=production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ember-temp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build --environment=production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ember-temp
npm ERR! Or if that isn't available, you can get their info via:

```

**Comment by krausest** [comment]
Hmm - I tried to clean and reinstall, but it works on my machine. I removed the local CSS files in 16cacb46a622a52af3c24e4fafcd4edf53575ce9 and the error you get obviously has to do with css so maybe you can check if it's fixed by now?

**Comment by krausest** [comment]
Closing this issue. The build works _currently_ (and I'm afraid I really have to add this) on OSX and Linux.
