### ISSUE TITLE
keyed/glimmer doesn't build anymore

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1388]
```
> glimmer@0.0.0 build-prod
> ember build --environment=production

WARNING: Node v18.17.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.
Environment: production
⠋ Buildingnode_modules/@glimmer/application/dist/types/src/test.d.ts(36,22): error TS2420: Class 'TestDelegate' incorrectly implements interface 'AppCompilerDelegate<any>'.
  Property 'getComponentLayout' is missing in type 'TestDelegate' but required in type 'AppCompilerDelegate<any>'.
node_modules/@glimmer/runtime/dist/types/lib/component/curried-component.d.ts(6,87): error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'CurriedComponentDefinition' is not assignable to type 'Maybe<Dict<unknown>>'.
    Type 'CurriedComponentDefinition' is not assignable to type 'Dict<unknown>'.
      Index signature is missing in type 'CurriedComponentDefinition'.
node_modules/@glimmer/util/dist/types/lib/destroy.d.ts(3,69): error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'SymbolDestroyable' is not assignable to type 'Maybe<Dict<unknown>>'.
    Type 'SymbolDestroyable' is not assignable to type 'Dict<unknown>'.
      Index signature is missing in type 'SymbolDestroyable'.
src/ui/components/PerformantEach/component.ts(6,15): error TS2556: Expected 2 arguments, but got 0 or more.
⠇ building... [RollupWithDependencies > rollup]Rollup warning:  'handlebars' is imported by node_modules/@glimmer/compiler/node_modules/@glimmer/syntax/dist/modules/es2017/lib/parser/tokenizer-event-handlers.js, but could not be resolved – treating it as an external dependency
⠏ building... [RollupWithDependencies > rollup]Rollup warning:  'handlebars' is imported by node_modules/@glimmer/syntax/dist/modules/es2017/lib/parser/tokenizer-event-handlers.js, but could not be resolved – treating it as an external dependency
cleaning up...
Build Error (RollupWithDependencies)

'hydrateProgram' is not exported by node_modules/@glimmer/program/dist/modules/es2017/index.js


Stack Trace and Error Report: /tmp/error.dump.f094f52d83182a3f9fde9e3f8f539898.log
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runCommand (file:///home/stefan/jfb2/rebuild-all.js:78:3)
    at buildFramework (file:///home/stefan/jfb2/rebuild-all.js:122:3)
    at buildFrameworks (file:///home/stefan/jfb2/rebuild-all.js:134:5)
    at file:///home/stefan/jfb2/rebuild-all.js:140:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 153824,
  stdout: null,
  stderr: null
}
```

The implementation has been moved to broken-frameworks folder.

**Comment by krausest** [comment]
Closing due to no activity.
