### ISSUE TITLE
keyed/mahal build is broken

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1389]
the ci build fails with node v18.18.0:
```
npm run build-prod

> mahal-app@1.0.0 build-prod
> npm run deploy && npm run copy:html


> mahal-app@1.0.0 deploy
> cross-env NODE_ENV=production webpack --config config/webpack/prod.config.js

assets by status 37 KiB [cached] 5 assets
Entrypoint main = js/runtime.8bf36938d9012d6ced34.bundle.js css/main.31d6cfe0.css js/main.b25e63bbc19689985de8.bundle.js
orphan modules 12 KiB (javascript) 937 bytes (runtime) [orphan] 13 modules
runtime modules 2.47 KiB 3 modules
cacheable modules 27.3 KiB (javascript) 1 bytes (css/mini-extract)
  modules by path ./node_modules/ 18.6 KiB
    ./node_modules/mahal/dist/npm.export.js 168 bytes [built] [code generated]
    ./node_modules/mahal/dist/mahal.min.commonjs2.js 18.3 KiB [built] [code generated]
    ./node_modules/@mahaljs/webpack-loader/lib/runtime/render_component.js 120 bytes [built] [code generated]
  modules by path ./src/ 8.7 KiB (javascript) 1 bytes (css/mini-extract)
    ./src/index.ts + 4 modules 8.7 KiB [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/@mahaljs/webpack-loader/lib/plugin/scoped_css_loader.js!./node_modules/@mahaljs/webpack-loader/lib/index.js!./src/app.mahal?mahal&type=style&lang=css&index=0&id=981abdf0&scoped= 1 bytes [built] [code generated]

ERROR in /home/stefan/jfb2/frameworks/keyed/mahal/src/app.mahal.ts
2:20-28
[tsl] ERROR in /home/stefan/jfb2/frameworks/keyed/mahal/src/app.mahal.ts(2,21)
      TS2724: '"mahal"' has no exported member named 'Children'. Did you mean 'children'?
ts-loader-default_0c5a263502dc9404

webpack 5.88.2 compiled with 1 error in 6507 ms
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runCommand (file:///home/stefan/jfb2/rebuild-all.js:78:3)
    at buildFramework (file:///home/stefan/jfb2/rebuild-all.js:122:3)
    at buildFrameworks (file:///home/stefan/jfb2/rebuild-all.js:134:5)
    at file:///home/stefan/jfb2/rebuild-all.js:140:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 161794,
  stdout: null,
  stderr: null
}
```
The implementation has been moved to broken-frameworks folder.
@ujjwalguptaofficial Can you take a look at it please?

**Comment by krausest** [comment]
Locking all caret version helped.

**Comment by krausest** [comment]
Sorry for the confusion. It builds again, but the output doesn't work.

**Comment by ujjwalguptaofficial** [comment]
Ok, I will have a look.
