### ISSUE TITLE
keyed/million build is broken

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1390]
the `npm ci && npm run build-prod` build fails with node v18.18.0:
```
npm run build-prod

> build-prod
> rollup -c

sh: 1: rollup: not found
```
There's no rollup in package-lock. If I add rollup then I get the following error
```
npm run build-prod

> build-prod
> rollup -c


src/main.jsx → dist/main.js...
[Million.js] Found unsupported import for block. Make sure blocks are imported from correctly.
> 1 | import { block, mapArray } from 'million';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | // prettier-ignore
  4 | const adjectives = ['pretty', 'large', 'big', 'small', 'tall', 'short', 'long', 'handsome', 'plain', 'quaint', 'clean', 'elegant', 'easy', 'angry', 'crazy', 'helpful', 'mushy', 'odd', 'unsightly', 'adorable', 'important', 'inexpensive', 'cheap', 'expensive', 'fancy'];

[Million.js] Found unsupported import for block. Make sure blocks are imported from correctly.
> 1 | import { block, mapArray } from 'million';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | // prettier-ignore
  4 | const adjectives = ['pretty', 'large', 'big', 'small', 'tall', 'short', 'long', 'handsome', 'plain', 'quaint', 'clean', 'elegant', 'easy', 'angry', 'crazy', 'helpful', 'mushy', 'odd', 'unsightly', 'adorable', 'important', 'inexpensive', 'cheap', 'expensive', 'fancy'];

[Million.js] Found unsupported import for block. Make sure blocks are imported from correctly.
> 1 | import { block, mapArray } from 'million';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | // prettier-ignore
  4 | const adjectives = ['pretty', 'large', 'big', 'small', 'tall', 'short', 'long', 'handsome', 'plain', 'quaint', 'clean', 'elegant', 'easy', 'angry', 'crazy', 'helpful', 'mushy', 'odd', 'unsightly', 'adorable', 'important', 'inexpensive', 'cheap', 'expensive', 'fancy'];

[Million.js] Found unsupported import for block. Make sure blocks are imported from correctly.
> 1 | import { block, mapArray } from 'million';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | // prettier-ignore
  4 | const adjectives = ['pretty', 'large', 'big', 'small', 'tall', 'short', 'long', 'handsome', 'plain', 'quaint', 'clean', 'elegant', 'easy', 'angry', 'crazy', 'helpful', 'mushy', 'odd', 'unsightly', 'adorable', 'important', 'inexpensive', 'cheap', 'expensive', 'fancy'];

[!] RollupError: Expression expected (Note that you need plugins to import files that are not JavaScript)
src/main.jsx (75:6)
73: };
74:
75: const select = (id) => {
          ^
76:   selected = id;
77:   update();
    at error (/home/stefan/jfb2/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:345:30)
    at Module.error (/home/stefan/jfb2/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:15995:16)
    at Module.tryParse (/home/stefan/jfb2/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:16726:25)
    at Module.setSource (/home/stefan/jfb2/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:16327:39)
    at ModuleLoader.addModuleSource (/home/stefan/jfb2/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:20586:20)
```
The implementation has been moved to broken-frameworks folder.
@aidenybai Can you please take a look at it?

**Comment by krausest** [comment]
I took another look at it, fixed all caret version and install rollup@3.29.4 and then the build worked again. I restored it.
