### ISSUE TITLE
Running the benchmarks，error reported during operation：fetch is not defined

### ISSUE THREAD

**Issue by maomincoding** [krausest/js-framework-benchmark#1437]
```
ReferenceError: fetch is not defined
    at fetchFrameworks (file:///E:/my/git/test-js-framework-benchmark-new/webdriver-ts/dist/common.js:36:26)
    at initializeFrameworks (file:///E:/my/git/test-js-framework-benchmark-new/webdriver-ts/dist/common.js:52:26)
    at main (file:///E:/my/git/test-js-framework-benchmark-new/webdriver-ts/dist/benchmarkRunner.js:291:28)
    at file:///E:/my/git/test-js-framework-benchmark-new/webdriver-ts/dist/benchmarkRunner.js:319:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
run was not completely sucessful Error: Error: ReferenceError: fetch is not defined
    at initializeFrameworks (file:///E:/my/git/test-js-framework-benchmark-new/webdriver-ts/dist/common.js:55:15)
    at async main (file:///E:/my/git/test-js-framework-benchmark-new/webdriver-ts/dist/benchmarkRunner.js:291:22)
```

I used the first method: Run pre build binaries for all frameworks

**Comment by krausest** [comment]
What's your nodejs version? It's currently tested with v20.8.0.

**Comment by maomincoding** [comment]
Yes, it's because of the node version. My version is 16.20.0, thank you
