### ISSUE TITLE
npm run bench keyed/vanillajs -> TypeError: fetch failed 

### ISSUE THREAD

**Issue by dy** [krausest/js-framework-benchmark#1458]
First, 4. from readme doesn't mention that it requires webdriver-ts to be compiled.
But now struggling with just 2.
After `npm i` both in root and in `webdriver-ts`, as well as `npm compile` in webdriver-ts, running  `npm run bench keyed/vanillajs` and getting this error:
```
npm run bench keyed/vanillajs

> js-framework-benchmark@1.0.0 bench
> cd webdriver-ts && cross-env LANG="en_US.UTF-8" node dist/benchmarkRunner.js keyed/vanillajs

PLEASE MAKE SURE THAT YOUR MOUSE IS OUTSIDE OF THE BROWSER WINDOW - and sorry for shouting :-) 
args {
  _: [
    '/usr/local/bin/node',
    '/Users/div/projects/js-framework-benchmark/webdriver-ts/dist/benchmarkRunner.js',
    'keyed/vanillajs'
  ],
  headless: false,
  nothrottling: false,
  runner: 'puppeteer',
  browser: 'chrome',
  '$0': 'dist/benchmarkRunner.js'
}
INFO: Using puppeteer benchmark runner
HEADLESS***  false
args {
  _: [
    '/usr/local/bin/node',
    '/Users/div/projects/js-framework-benchmark/webdriver-ts/dist/benchmarkRunner.js',
    'keyed/vanillajs'
  ],
  headless: false,
  nothrottling: false,
  runner: 'puppeteer',
  browser: 'chrome',
  '$0': 'dist/benchmarkRunner.js'
} allArgs [ 'keyed/vanillajs' ]
benchmarkOptions {
  port: 8080,
  host: 'localhost',
  browser: 'chrome',
  remoteDebuggingPort: 9999,
  chromePort: 9998,
  headless: false,
  chromeBinaryPath: undefined,
  numIterationsForCPUBenchmarks: 15,
  numIterationsForMemBenchmarks: 1,
  numIterationsForStartupBenchmark: 1,
  batchSize: 1,
  resultsDirectory: 'results',
  tracesDirectory: 'traces',
  allowThrottling: true
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchFrameworks (file:///Users/div/projects/js-framework-benchmark/webdriver-ts/dist/common.js:36:26)
    at async initializeFrameworks (file:///Users/div/projects/js-framework-benchmark/webdriver-ts/dist/common.js:52:20)
    at async main (file:///Users/div/projects/js-framework-benchmark/webdriver-ts/dist/benchmarkRunner.js:310:22) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8080
  }
}
run was not completely sucessful Error: Error: TypeError: fetch failed
    at initializeFrameworks (file:///Users/div/projects/js-framework-benchmark/webdriver-ts/dist/common.js:55:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/div/projects/js-framework-benchmark/webdriver-ts/dist/benchmarkRunner.js:310:22)
```

Nothing is running on that port.

Would you be able to give a hint what's wrong?

**Comment by krausest** [comment]
I'm pretty sure your node version is too old. Please update to node v20 (tested with v20.8.0) and report back if it works.

**Comment by krausest** [comment]
Actually I'm not so sure anymore :)
Did you start the server? (Section 1.2 in the README).
Please start with `npm start` in the root of the js-framework-benchmark directory and let it running in the background.

**Comment by krausest** [comment]
I checked the README: The compile step for webdriver-ts is included in `npm run install-local` in step 1.2 and `npm run compile` is also mentioned in 2.4.
Please let me know If you have a suggestion how to describe it clearer.

**Comment by dy** [comment]
Ok, pulled latest version of repository, switched node to latest, installed all deps, run a few benches, but now after producing results via `npm run results`, navigating to `http://localhost:8080/webdriver-ts-results`
```
{"message":"Route GET:/webdriver-ts-results/table.html not found","error":"Not Found","statusCode":404}
```

**Comment by dy** [comment]
> Please let me know If you have a suggestion how to describe it clearer.

I think it would be nice to have a note in 4.1.1 to `cd webdriver-ts && npm i`
