### ISSUE TITLE
Update better-react

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1788]
I'm trying to update (the next week or so) all frameworks to the next major version.
Updating better-react failed with the following error. It was moved to the broken-frameworks folder. 
@wyknmjj   Can you take a look at it please?
```
> node cli.js rebuild-single -f keyed/better-react

Rebuild single: ci false frameworks [ 'keyed/better-react' ]
Rebuild build single: useCi false frameworks [ 'keyed/better-react' ]
Rebuilding framework keyed/better-react
Deleted: yarn-lock,dist,elm-stuff,bower_components,node_modules,output,package-lock.json
running 'npm install' in 'frameworks/keyed/better-react'

added 18 packages, and audited 19 packages in 56s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
running 'npm run build-prod' in 'frameworks/keyed/better-react'

> better-react@0.0.0 build-prod
> vite build

vite v6.0.3 building for production...
✓ 4 modules transformed.
x Build failed in 226ms
error during build:
[commonjs--resolver] Missing "./Vue" specifier in "wy-helper" package
    at e (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:15108:25)
    at n (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:15108:627)
    at o (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:15108:1297)
    at resolveExportsOrImports (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:16306:18)
    at resolveDeepImport (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:16319:25)
    at tryNodeResolve (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:16149:18)
    at Object.resolveId (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:15934:19)
    at Object.handler (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:50806:15)
    at file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/rollup/dist/es/shared/node-entry.js:20812:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/stefan/js-framework-benchmark/frameworks/keyed/better-react/node_modules/rollup/dist/es/shared/node-entry.js:20712:28)
ERROR Error: Command failed: npm run build-prod
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at runCommand (file:///home/stefan/js-framework-benchmark/cli/rebuild-build-single.js:30:3)
    at rebuildFramework (file:///home/stefan/js-framework-benchmark/cli/rebuild-build-single.js:70:3)
    at rebuildFrameworks (file:///home/stefan/js-framework-benchmark/cli/rebuild-build-single.js:86:5)
    at rebuildSingleFramework (file:///home/stefan/js-framework-benchmark/cli/rebuild-single-framework.js:33:5)
    at Command.<anonymous> (file:///home/stefan/js-framework-benchmark/cli.js:70:5)
    at Command.listener [as _actionHandler] (/home/stefan/js-framework-benchmark/node_modules/commander/lib/command.js:542:17) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 151178,
  stdout: null,
  stderr: null
}
ERROR: Rebuilding  keyed/better-react was not successful
```

**Comment by krausest** [comment]
I'm closing the issue due to inactivity.
