### ISSUE TITLE
Updating ember fails

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1793]
As in #1789 I'm updating all implementations. For ember I went the `npm uninstall ember-cli,
npm install ember-cli, ember update` route but the app prints the following error:
```
ember.js:5917 Uncaught TypeError: Cannot destructure property 'manager' of 'e' as it is null.
    at Lp.resolvedComponent (ember.js:5917:1)
    at ember.js:1247:1
    at Fs (ember.js:1247:1)
    at a (ember.js:1498:1)
    at ember.js:1492:1
    at Ys.compile (ember.js:1286:1)
    at Rl (ember.js:1498:1)
    at ember.js:1498:1
    at Ol.compile (ember.js:1498:1)
    at Object.evaluate (ember.js:6048:1)
```
It was moved to the broken-frameworks folder.
@NullVoxPopuli Can you take a look at it please?

**Comment by NullVoxPopuli** [comment]
What node are you using?
From what directory did you run the command?

**Comment by krausest** [comment]
It's node v20.17.0 in the implementation's root directory keyed/ember (but I ran it from ./node_modules/.bin/ember, not from a global installation)

**Comment by NullVoxPopuli** [comment]
Thanks, i'll take a look later today

**Comment by krausest** [comment]
We merged ember 6.4 recently
