### ISSUE TITLE
Updating keyed/fre failed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1794]
As in #1789 I'm updating all implementations. Implementations that failed to update are moved in to the broken-frameworks folder.
The build works fine for fre 2.6.5, but the swap rows test fails with a runtime error:
```
main.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'insertBefore')
    at L (main.js:5:2168)
    at L (main.js:5:2343)
    at L (main.js:5:2332)
    at L (main.js:5:2332)
    at L (main.js:5:2343)
    at L (main.js:5:2332)
    at L (main.js:5:2332)
    at P (main.js:5:3076)
    at G (main.js:5:3021)
    at B (main.js:5:2725)
L @ main.js:5
L @ main.js:5
L @ main.js:5
L @ main.js:5
L @ main.js:5
L @ main.js:5
L @ main.js:5
P @ main.js:5
G @ main.js:5
B @ main.js:5
M @ main.js:5
(anonymous) @ main.js:5
t @ main.js:5Understand this errorAI
main.js:5 Uncaught TypeError: t is not a function
    at M (main.js:5:1929)
    at main.js:5:1600
    at Array.forEach (<anonymous>)
    at MessagePort.t (main.js:5:1589)
```
@yisar Can you take a look at this?

**Comment by yisar** [comment]
Thanks for your work. I don't have time to fix this issue because I have a final exam. After I finish the exam, I will submit a new version, and you can temporarily take it down.

**Comment by krausest** [comment]
Good luck for your exam!
