### ISSUE TITLE
Updating keyed/million failed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1798]
As in #1789 I'm updating all implementations. Implementations that failed to update are moved in to the broken-frameworks folder.
Here's what I'm trying to update:
```
-    "million": "2.3.3",
+    "million": "3.1.11",
 ```
The build fails with the following build error:
```
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/main.jsx (88:2)
86: 
87: const Main = block(({ rows }) => (
88:   <div class="container">
      ^
89:     <div class="jumbotron">
90:       <div class="row">
    at error (/home/stefan/js-framework-benchmark/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:353:30)
    at Module.error (/home/stefan/js-framework-benchmark/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:15237:16)
    at Module.tryParse (/home/stefan/js-framework-benchmark/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:15968:25)
    at Module.setSource (/home/stefan/js-framework-benchmark/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:15569:39)
    at ModuleLoader.addModuleSource (/home/stefan/js-framework-benchmark/frameworks/keyed/million/node_modules/rollup/dist/shared/rollup.js:25804:20)
```
@aidenybai Can you take a look at this?

**Comment by krausest** [comment]
I'm closing the issue due to inactivity.
