### ISSUE TITLE
Updating keyed/react-jotai failed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1801]
As in #1789 I'm updating all implementations. Implementations that failed to update are moved in to the broken-frameworks folder.
Here's what I'm trying to update:
```
-    "jotai": "1.7.2",
+    "jotai": "2.10.3",
 ```
The build fails with the following runtime error:
```
main.js:2 TypeError: (0 , r.useUpdateAtom) is not a function
    at ne (main.js:2:138551)
    at ao (main.js:2:59860)
    at Qu (main.js:2:111707)
    at Ni (main.js:2:99055)
    at Ci (main.js:2:98983)
    at xi (main.js:2:98846)
    at gi (main.js:2:95843)
    at di (main.js:2:93233)
    at Gi (main.js:2:109048)
    at main.js:2:110434
iu @ main.js:2
n.callback @ main.js:2
pa @ main.js:2
mu @ main.js:2
Li @ main.js:2
t.unstable_runWithPriority @ main.js:2
Hl @ main.js:2
zi @ main.js:2
gi @ main.js:2
di @ main.js:2
Gi @ main.js:2
(anonymous) @ main.js:2
bi @ main.js:2
rs @ main.js:2
t.render @ main.js:2
(anonymous) @ main.js:2
(anonymous) @ main.js:2Understand this errorAI
main.js:2 Uncaught TypeError: (0 , r.useUpdateAtom) is not a function
    at ne (main.js:2:138551)
    at ao (main.js:2:59860)
    at Qu (main.js:2:111707)
    at Ni (main.js:2:99055)
    at Ci (main.js:2:98983)
    at xi (main.js:2:98846)
    at gi (main.js:2:95843)
    at di (main.js:2:93233)
    at Gi (main.js:2:109048)
    at main.js:2:110434
}
```
@Thisen  Can you take a look at this?

**Comment by krausest** [comment]
I'm closing the issue due to inactivity.
