### ISSUE TITLE
Updating keyed/reflex-js-atomic failed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1802]
As in #1789 I'm updating all implementations. Implementations that failed to update are moved in to the broken-frameworks folder.
Here's what I'm trying to update:
```
-    "reflex-dom": "0.23.1"
+    "reflex-dom": "0.25.3"
 ```
The build fails with the following runtime error when deleting a row:
```
main.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '_')
    at _detachEffectFromStates (main.js:1:7240)
    at main.js:1:7815
    at _dispatch (main.js:1:179)
    at recursivelyUpdateMountState (main.js:1:3443)
    at _removeNode (main.js:1:3763)
    at _diffChildren (main.js:1:4550)
    at diffNode (main.js:1:5988)
    at _diffChildren (main.js:1:4833)
    at diffNode (main.js:1:5988)
    at diffNode (main.js:1:5888)
```
@zouloux  Can you take a look at this?

**Comment by zouloux** [comment]
Hi, sorry for the delay. I'll definitively check that, thanks for the feedback

**Comment by krausest** [comment]
I'm closing the issue due to inactivity.
