### ISSUE TITLE
Updating keyed/voby failed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1804]
As in #1789 I'm updating all implementations. Implementations that failed to update are moved in to the broken-frameworks folder.
Here's what I'm trying to update:
```
 -    "voby": "0.48.0"
+    "voby": "0.58.1"
```
The build fails with the following runtime error:
```
main.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at main.js:2:32036
    at n (main.js:2:31916)
    at main.js:2:33615
    at Ro (main.js:2:33692)
    at main.js:2:35120
    at main.js:2:36376
    ```
@fabiospampinato  Can you take a look at this?

**Comment by fabiospampinato** [comment]
I'll have a look but why are you expecting updating stuff across versions containing potentially breaking changes to just work?

**Comment by krausest** [comment]
Not sure if I expect it but I'm hoping on backwards compatibility, I guess that's what most users do 😄. 
I really want to keep implementations more current otherwise their benchmark is worthless. 
I'm not sure on the update interval but something like twice a year or so seems sensible. 

What I can do is trying to update with ncu (and if it fails I try to just bump the framework version and not the bundlers and transpilers). For the big frameworks there are release notes which I'm trying to apply (like angular, react and ember).

**Comment by fabiospampinato** [comment]
> Not sure if I expect it but I'm hoping on backwards compatibility, I guess that's what most users do 😄.

Backwards compatibility across versions that can semantically have backwards incompatible changes? Like according to semantic versioning minor releases can contain breaking changes for 0.x.x version numbers.

**Comment by krausest** [comment]
Seems to me that the point of this nit-picking discussion is rather the process than semantic versioning.

What's your expectation on the update process in this benchmark? 
Should we try to keep versions up to date?
How should the implementations be updated (especially when simply bumping the versions causes a broken build)?

**Comment by fabiospampinato** [comment]
It seems a good idea to try to keep implementations updated, maybe with some kind of rule that says that every implementation can't be more than 1 or 2 years old or something, or it will not be shown to the user by default maybe. I'll update mine hopefully at some point in january.

**Comment by krausest** [comment]
Great to hear - thanks!

**Comment by krausest** [comment]
I'm just iterating over the non-keyed entries too. Could you please update the non-keyed version too?

**Comment by krausest** [comment]
I'm closing the issue due to inactivity.
