### ISSUE TITLE
Glimmer build fails (only with yarn)

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#182]
Glimmer doesn't building with the following message when packages are installed with `yarn install`, installing with `npm install` works. I changed package.json to have fixed version numbers to facilitate reproducible builds.
@rwjblue Any help would be very appreciated how to fix it.

Stefans-MBP:glimmer-v0.3.10 stefan$ npm run build-prod

> glimmer-app@0.0.0 build-prod /Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10
> ember build --environment=production

Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
⠋ BuildingClass constructor AbstractBuild cannot be invoked without 'new'
TypeError: Class constructor AbstractBuild cannot be invoked without 'new'
    at new GlimmerApp (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:111:24)
    at module.exports (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/ember-cli-build.js:6:13)
    at Builder.setupBroccoliBuilder (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/stefan/Source/Javascript/js-framework-benchmark/glimmer-v0.3.10/node_modules/rsvp/dist/rsvp.js:2414:5)

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/stefan/.nvm/versions/node/v7.0.0/bin/node" "/Users/stefan/.nvm/versions/node/v7.0.0/bin/npm" "run" "build-prod"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! glimmer-app@0.0.0 build-prod: `ember build --environment=production`
npm ERR! Exit status 1
npm ERR!

**Comment by rwjblue** [comment]
@krausest - Upstream issue was fixed this morning. `yarn upgrade ember-build-utilities` should do the trick.
