### ISSUE TITLE
Error with npm run build 

### ISSUE THREAD

**Issue by kavoos** [krausest/js-framework-benchmark#189]
I got this error after running `npm run build` . Am I doing something wrong? :(
```
Executing npm run build-prod in marko-v4.3.0

> js-framework-benchmark-marko@1.1.1 build-prod C:\Users\Kavoos\Documents\WebappsProjects\bachelor thesis\js-framework-benchmark\marko-v4.3.0
> NODE_ENV=production rollup -c rollup.config.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark-marko@1.1.1 build-prod: `NODE_ENV=production rollup -c rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark-marko@1.1.1 build-prod script 'NODE_ENV=production rollup -c rollup.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark-marko package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production rollup -c rollup.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark-marko
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark-marko
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kavoos\AppData\Roaming\npm-cache\_logs\2017-05-30T05_26_55_479Z-debug.log
child_process.js:533
    throw err;
    ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at C:\Users\Kavoos\Documents\WebappsProjects\bachelor thesis\js-framework-benchmark\build.js:10:3
    at arrayEach (C:\Users\Kavoos\Documents\WebappsProjects\bachelor thesis\js-framework-benchmark\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\Users\Kavoos\Documents\WebappsProjects\bachelor thesis\js-framework-benchmark\node_modules\lodash\lodash.js:9359:14)
    at Object.<anonymous> (C:\Users\Kavoos\Documents\WebappsProjects\bachelor thesis\js-framework-benchmark\build.js:7:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark@1.0.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark@1.0.0 build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kavoos\AppData\Roaming\npm-cache\_logs\2017-05-30T05_26_55_515Z-debug.log

```

**Comment by krausest** [comment]
Sorry. I build on osx, check regularly on linux and rarely on windows. The windows build for marko and stem.js failed. It's fixed now.
Simply pull the changes, open build.js and change the line `var restartWithFramework = '';` to `var restartWithFramework = 'marko';` and the build should resume.
If you run into other problems please report here. (If you don't want to wait for my response you can move the folder of the framework that caused the problem away and resume the build.)

**Comment by kavoos** [comment]
@krausest , thanks for the fast response. The previous error is solved but now I get this one when I run `npm run selenium` in the root directory. I just want to see result of angular-v2, ember and react (all keyed). I also tried `npm run selenium -- --framework angular-v2.4.9-keyed,ember-v2.13.0,react-v15.5.4-keyed --benchmark` and got the same error :(

```
...
Benchmarks that will be run [ '01_run1k',
  '02_replace1k',
  '03_update10th1k',
  '04_select1k',
  '05_swap1k',
  '06_remove-one-1k',
  '07_create10k',
  '08_create1k-after10k',
  '09_clear10k',
  '21_ready-memory',
  '22_run-memory',
  '30_startup' ]
benchmarking  { name: 'angular-v1.6.3-keyed',
  nonKeyed: false,
  uri: 'angular-v1.6.3-keyed',
  useShadowRoot: false } 01_run1k
C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\lib\promise.js:2634
        throw error;
        ^

WebDriverError: unknown error: no chrome binary at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.14393 x86_64)
    at Object.checkLegacyResponse (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\chrome.js:719:29)
    at createDriver (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\index.js:639:16)
    at buildDriver (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\dist\benchmarkRunner.js:73:10)
    at runMemOrCPUBenchmark (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\dist\benchmarkRunner.js:167:18)
    at webdriverAccess_1.forProm (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\dist\benchmarkRunner.js:229:20)
    at forPromRec (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\dist\webdriverAccess.js:122:16)
    at Object.forProm (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\dist\webdriverAccess.js:128:12)
    at runBench (C:\Users\Kavoos\Documents\WebappsProjects\Benchmark\js-framework-benchmark\webdriver-ts\dist\benchmarkRunner.js:222:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriver-ts@1.0.0 selenium: `node dist/benchmarkRunner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriver-ts@1.0.0 selenium script 'node dist/benchmarkRunner.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webdriver-ts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/benchmarkRunner.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webdriver-ts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webdriver-ts
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kavoos\AppData\Roaming\npm-cache\_logs\2017-05-30T21_07_14_915Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark@1.0.0 selenium: `cd webdriver-ts && npm run selenium && npm run results`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark@1.0.0 selenium script 'cd webdriver-ts && npm run selenium && npm run results'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd webdriver-ts && npm run selenium && npm run results
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.
```

**Comment by krausest** [comment]
I removed the path to chrome in commit https://github.com/krausest/js-framework-benchmark/commit/462907a2c88d51ddfe7c4a71501f11f2d8c88d75 
If chrome doesn't start you might need to set that variable to point at your chrome executable.
Just pull the changes, cd to webdriver-ts and run `npm run build-prod` and `npm run selenium` and check if it works now.

**Comment by krausest** [comment]
Closing this issue.
