### ISSUE TITLE
webdriver-ts-results problem build

### ISSUE THREAD

**Issue by splincode** [krausest/js-framework-benchmark#200]
```
ts-loader: Using typescript@2.4.1 and /home/splincode/Develop/js-framework-benchmark/webdriver-ts-results/tsconfig.json
Hash: d1b83457711d1cdad79b
Version: webpack 2.5.1
Child
    Hash: d1b83457711d1cdad79b
    Time: 12213ms
                                   Asset     Size  Chunks                    Chunk Names
    f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]         
    89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]         
    e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]         
                                 main.js   754 kB       0  [emitted]  [big]  main
                              table.html   755 kB          [emitted]  [big]  
      [39] ./~/react/react.js 56 bytes {0} [built]
      [61] ./~/react/lib/React.js 3.32 kB {0} [built]
      [88] ./src/App.css 994 bytes {0} [built]
     [134] ./src/Common.tsx 12.9 kB {0} [built]
     [195] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
     [196] ./~/react-dom/index.js 59 bytes {0} [built]
     [197] ./~/bootstrap/dist/css/bootstrap.css 984 bytes {0} [built]
     [198] ./src/ResultTable.tsx 6.9 kB {0} [built]
     [199] ./src/SelectBar.tsx 7.29 kB {0} [built]
     [200] ./src/results.ts 370 kB {0} [built]
     [479] ./src/App.tsx 13.7 kB {0} [built] [2 errors]
     [480] ./src/DropDown.tsx 1.05 kB {0} [built]
     [481] ./src/DropDownContents.tsx 1.06 kB {0} [built]
     [482] ./src/SelectBarBenchmarks.tsx 671 bytes {0} [built]
     [483] ./src/SelectBarFrameworks.tsx 671 bytes {0} [built]
        + 471 hidden modules
    
    ERROR in ./src/App.tsx
    (157,9): error TS2605: JSX element type 'SelectBar' is not a constructor function for JSX elements.
      Types of property 'setState' are incompatible.
        Type '{ <K extends never>(f: (prevState: void, props: Props) => Pick<void, K>, callback?: (() => any) |...' is not assignable to type '{ <K extends never>(f: (prevState: {}, props: any) => Pick<{}, K>, callback?: (() => any) | undef...'.
          Types of parameters 'f' and 'f' are incompatible.
            Types of parameters 'prevState' and 'prevState' are incompatible.
              Type 'void' is not assignable to type '{}'.
    
    ERROR in ./src/App.tsx
    (181,11): error TS2605: JSX element type 'ResultTable' is not a constructor function for JSX elements.
      Types of property 'setState' are incompatible.
        Type '{ <K extends never>(f: (prevState: void, props: Props) => Pick<void, K>, callback?: (() => any) |...' is not assignable to type '{ <K extends never>(f: (prevState: {}, props: any) => Pick<{}, K>, callback?: (() => any) | undef...'.
          Types of parameters 'f' and 'f' are incompatible.
            Types of parameters 'prevState' and 'prevState' are incompatible.
              Type 'void' is not assignable to type '{}'.
    
    ERROR in ./src/Common.tsx
    Module not found: Error: Can't resolve 'jstat' in '/home/splincode/Develop/js-framework-benchmark/webdriver-ts-results/src'
     @ ./src/Common.tsx 4:12-28
     @ ./src/App.tsx
    Child html-webpack-plugin for "table.html":
           [0] ./~/lodash/lodash.js 540 kB {0} [built]
           [1] ./~/html-webpack-plugin/lib/loader.js!./index.html 675 bytes {0} [built]
           [2] (webpack)/buildin/global.js 509 bytes {0} [built]
           [3] (webpack)/buildin/module.js 517 bytes {0} [built]

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-prod"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! js-framework-benchmark-react@1.1.1 build-prod: `cross-env NODE_ENV="production" webpack -p && cpx dist/table.html .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the js-framework-benchmark-react@1.1.1 build-prod script 'cross-env NODE_ENV="production" webpack -p && cpx dist/table.html .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV="production" webpack -p && cpx dist/table.html .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/splincode/.npm/_logs/2017-06-30T20_14_53_154Z-debug.log
child_process.js:524
    throw err;
    ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at /home/splincode/Develop/js-framework-benchmark/build.js:18:4
    at arrayEach (/home/splincode/Develop/js-framework-benchmark/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/splincode/Develop/js-framework-benchmark/node_modules/lodash/lodash.js:9359:14)
    at Object.<anonymous> (/home/splincode/Develop/js-framework-benchmark/build.js:12:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark@1.0.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-framework-benchmark@1.0.0 build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/splincode/.npm/_logs/2017-06-30T20_14_53_199Z-debug.log


```

**Comment by krausest** [comment]
Hmm - your log tells that you're using typescript@2.4.1.  The package.json installs typescript locally and npm should use the local version. Do you have typescript installed globally? Seems like I should prefix all commands with `./node_modules/.bin/`

Anyways typescript 2.4.1 reports the error you mentioned and I fixed that and updated typescript to 2.4.1 - so it should work now again.

I'm leaving this bug open until I've prefixed all commands.

**Comment by splincode** [comment]
```


> js-framework-benchmark-angular@1.0.0 build-prod /home/splincode/Develop/js-framework-benchmark/angular-v1.6.3-keyed
> webpack -p

[BABEL] Note: The code generator has deoptimised the styling of "/home/splincode/Develop/js-framework-benchmark/angular-v1.6.3-keyed/node_modules/angular/angular.js" as it exceeds the max of "500KB".
Hash: 98033df6b514960d4456
Version: webpack 2.2.1
Time: 10915ms
  Asset    Size  Chunks                    Chunk Names
main.js  268 kB       0  [emitted]  [big]  main
   [0] ./~/angular/index.js 62 bytes {0} [built]
   [1] ./~/jquery/dist/jquery.js 272 kB {0} [built]
   [2] ./src/home.controller.js 5 kB {0} [built]
   [3] ./~/angular/angular.js 1.12 MB {0} [built]
   [4] (webpack)/buildin/module.js 521 bytes {0} [built]
   [5] ./src/main.js 591 bytes {0} [built]
build true restartWithFramework  true
Executing npm run build-prod in angular-v4.1.2-keyed

> angular2-webpack@1.0.0 build-prod /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-keyed
> npm run precompile && npm run closure


> angular2-webpack@1.0.0 precompile /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-keyed
> ngc


> angular2-webpack@1.0.0 preclosure /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-keyed
> rm -rf dist


> angular2-webpack@1.0.0 closure /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-keyed
> java -jar node_modules/google-closure-compiler/compiler.jar --flagfile closure.conf

build true restartWithFramework  true
Executing npm run build-prod in angular-v4.1.2-non-keyed

> angular2-webpack@1.0.0 build-prod /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-non-keyed
> npm run precompile && npm run closure


> angular2-webpack@1.0.0 precompile /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-non-keyed
> ngc


> angular2-webpack@1.0.0 preclosure /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-non-keyed
> rm -rf dist


> angular2-webpack@1.0.0 closure /home/splincode/Develop/js-framework-benchmark/angular-v4.1.2-non-keyed
> java -jar node_modules/google-closure-compiler/compiler.jar --flagfile closure.conf

build true restartWithFramework  true
Executing npm run build-prod in aurelia-v1.1.2

> js-framework-benchmark-aurelia@1.0.0 prebuild-prod /home/splincode/Develop/js-framework-benchmark/aurelia-v1.1.2
> npm run clean:dist


> js-framework-benchmark-aurelia@1.0.0 clean:dist /home/splincode/Develop/js-framework-benchmark/aurelia-v1.1.2
> rimraf dist


> js-framework-benchmark-aurelia@1.0.0 build-prod /home/splincode/Develop/js-framework-benchmark/aurelia-v1.1.2
> cross-env NODE_ENV=production npm run webpack -- --progress --profile


> js-framework-benchmark-aurelia@1.0.0 webpack /home/splincode/Develop/js-framework-benchmark/aurelia-v1.1.2
> cross-env BABEL_ENV=node ./node_modules/.bin/webpack "--progress" "--profile"

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/splincode/.babel.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at save (/home/splincode/Develop/js-framework-benchmark/aurelia-v1.1.2/node_modules/babel-register/lib/cache.js:48:16)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack" "--" "--progress" "--profile"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark-aurelia@1.0.0 webpack: `cross-env BABEL_ENV=node ./node_modules/.bin/webpack "--progress" "--profile"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-framework-benchmark-aurelia@1.0.0 webpack script 'cross-env BABEL_ENV=node ./node_modules/.bin/webpack "--progress" "--profile"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark-aurelia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=node ./node_modules/.bin/webpack "--progress" "--profile"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark-aurelia
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark-aurelia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/splincode/.npm/_logs/2017-07-01T19_53_05_899Z-debug.log

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-prod"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark-aurelia@1.0.0 build-prod: `cross-env NODE_ENV=production npm run webpack -- --progress --profile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-framework-benchmark-aurelia@1.0.0 build-prod script 'cross-env NODE_ENV=production npm run webpack -- --progress --profile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark-aurelia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production npm run webpack -- --progress --profile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark-aurelia
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark-aurelia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/splincode/.npm/_logs/2017-07-01T19_53_05_941Z-debug.log
child_process.js:524
    throw err;
    ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at /home/splincode/Develop/js-framework-benchmark/build.js:18:4
    at arrayEach (/home/splincode/Develop/js-framework-benchmark/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/splincode/Develop/js-framework-benchmark/node_modules/lodash/lodash.js:9359:14)
    at Object.<anonymous> (/home/splincode/Develop/js-framework-benchmark/build.js:12:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark@1.0.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-framework-benchmark@1.0.0 build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/splincode/.npm/_logs/2017-07-01T19_53_05_998Z-debug.log


```

**Comment by alexteves** [comment]
I also encountered the errors in the first post:

`Types of property 'setState' are incompatible.`
These two went away with the typescript update commit.

`Module not found: Error: Can't resolve 'jstat' in '/home/splincode/Develop/js-framework-benchmark/webdriver-ts-results/src'`
[This is due to incorrect casing](https://github.com/krausest/js-framework-benchmark/pull/201/files#diff-bf3a46d711573222e72d6015cff2c66cR2).

Never saw the error in the second post, though.

**Comment by krausest** [comment]
Now I can say that the build works fine on [travis-ci](https://travis-ci.org/krausest/js-framework-benchmark).
@splincode I don't know what's going on in your build and why there's a "permission denied, open '/home/splincode/.babel.json'" on your machine. I guess you have some of the dependencies installed globally. For building the tests here I suggest having only the [prerequisites](https://github.com/krausest/js-framework-benchmark#prerequisites) installed globally.
The jStat case sensivity error went unnoticed on my mac - thanks to travis there's a chance that won't happen again.

**Comment by krausest** [comment]
I really don't understand what's going on on your machine. Even when typescript is globally installed it works fine
```
Stefans-MBP:webdriver-ts-results stefan$ tsc --version
Version **2.4.1**
Stefans-MBP:webdriver-ts-results stefan$ ./node_modules/.bin/tsc --version
Version **2.3.3**
Stefans-MBP:webdriver-ts-results stefan$ npm run build-prod

> js-framework-benchmark-react@1.1.1 build-prod /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts-results
> cross-env NODE_ENV="production" webpack -p && cpx dist/table.html .

ts-loader: Using typescript@**2.3.3** and /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts-results/tsconfig.json
```
The ts-loader uses the correct, locally installed version, same goes for webpack:

I installed webpack 3 globally:
```
Stefans-MBP:webdriver-ts stefan$ webpack --version
**3.0.0**
```
But my build uses the correct wepack version:
```
js-framework-benchmark-react@1.1.1 build-prod /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts-results
> cross-env NODE_ENV="production" webpack -p && cpx dist/table.html .

ts-loader: Using typescript@2.3.3 and /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts-results/tsconfig.json
Hash: e57026b8744a5349cd6b
Version: webpack **2.5.1**
```

**Comment by splincode** [comment]
Why do not you use the online test demonstration? So you do not need to run it locally

**Comment by krausest** [comment]
Not sure I understand (actually I'm pretty sure I don't understand) - you tried to build it locally which works fine for me and travis-ci...
