### ISSUE TITLE
Building (npm run build) doesn't work

### ISSUE THREAD

**Issue by lega911** [krausest/js-framework-benchmark#42]
Hello!
Building doesn't work, it's log I have

```
# node --version
v6.4.0

# git clone https://github.com/krausest/js-framework-benchmark
# cd js-framework-benchmark/

# npm install
# npm run build

> js-framework-benchmark@1.0.0 build /tmp/0/js-framework-benchmark
> node build.js


> js-framework-benchmark-angular@1.0.0 build-prod /tmp/0/js-framework-benchmark/angular-v1.5.7
> webpack -p -c webpack.config.js

sh: 1: webpack: not found

npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-prod"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! js-framework-benchmark-angular@1.0.0 build-prod: `webpack -p -c webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the js-framework-benchmark-angular@1.0.0 build-prod script 'webpack -p -c webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark-angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p -c webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark-angular
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark-angular
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/0/js-framework-benchmark/angular-v1.5.7/npm-debug.log
child_process.js:526
    throw err;
    ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at /tmp/0/js-framework-benchmark/build.js:7:3
    at arrayEach (/tmp/0/js-framework-benchmark/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/tmp/0/js-framework-benchmark/node_modules/lodash/lodash.js:9011:14)
    at Object.<anonymous> (/tmp/0/js-framework-benchmark/build.js:5:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! js-framework-benchmark@1.0.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-framework-benchmark@1.0.0 build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/0/js-framework-benchmark/npm-debug.log
```

**Comment by lega911** [comment]
even if I npm install: webpack babel-loader babel-core babel-preset-es2015, it gives me errors:
```
# npm run build

> js-framework-benchmark@1.0.0 build /tmp/0/js-framework-benchmark
> node build.js


> js-framework-benchmark-angular@1.0.0 build-prod /tmp/0/js-framework-benchmark/angular-v1.5.7
> webpack -p -c webpack.config.js

Hash: bd2ffe00e4b69f2455e7
Version: webpack 1.13.2
Child
    Hash: bd2ffe00e4b69f2455e7
    Version: webpack 1.13.2
    Time: 2704ms
      Asset     Size  Chunks             Chunk Names
    main.js  90.9 kB       0  [emitted]  main
       [0] multi main 40 bytes {0} [built]
       [1] ./src/angularmin.js 75 bytes {0} [built] [1 error]
       [2] ./webpack.config.js 525 bytes {0} [built]
        + 3 hidden modules
    
    WARNING in main.js from UglifyJs
    Side effects in initialization of unused variable jQuery [./src/main.es6.js:3,4]
    Condition always true [../~/jquery/dist/jquery.js:10035,0]
    
    ERROR in ./src/angularmin.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./../node_modules/angular/angular.min in /tmp/0/js-framework-benchmark/angular-v1.5.7/src
     @ ./src/angularmin.js 1:0-48

> angular2-webpack@1.0.0 build-prod /tmp/0/js-framework-benchmark/angular-v2.0.0-rc4
> webpack --config config/webpack.prod.js --progress --profile --bail

module.js:457
    throw err;
    ^

Error: Cannot find module 'webpack-merge'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/0/js-framework-benchmark/angular-v2.0.0-rc4/config/webpack.prod.js:2:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-prod"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack@1.0.0 build-prod: `webpack --config config/webpack.prod.js --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack@1.0.0 build-prod script 'webpack --config config/webpack.prod.js --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config config/webpack.prod.js --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/0/js-framework-benchmark/angular-v2.0.0-rc4/npm-debug.log
child_process.js:526
    throw err;
    ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at /tmp/0/js-framework-benchmark/build.js:7:3
    at arrayEach (/tmp/0/js-framework-benchmark/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/tmp/0/js-framework-benchmark/node_modules/lodash/lodash.js:9011:14)
    at Object.<anonymous> (/tmp/0/js-framework-benchmark/build.js:5:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! js-framework-benchmark@1.0.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-framework-benchmark@1.0.0 build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/0/js-framework-benchmark/npm-debug.log

```

**Comment by lega911** [comment]
I run it in docker (isolation), it seems npm works wrongly from root
