### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by hbfs** [krausest/js-framework-benchmark#57]
did a brew update.. Have the latest everything.. should I just revert to infero@1.0.0-alpha8 ? or do I need to manually add a repo?
````
> ember-temp@0.0.0 postinstall ~/Downloads/js-framework-benchmark/ember-v2.6.1
> bower install

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! No compatible version found: inferno@1.0.0-alpha9
npm ERR! Valid install targets:
npm ERR! 1.0.0-alpha8, 1.0.0-alpha7, 1.0.0-alpha5, 1.0.0-alpha4, 1.0.0-alpha3, 1.0.0-alpha2, 1.0.0-alpha11, 1.0.0-alpha10, 1.0.0-alpha1, 0.8.0-alpha6, 0.8.0-alpha4, 0.8.0-alpha3, 0.8.0-alpha2, 0.8.0-alpha1, 0.7.27, 0.7.26, 0.7.25, 0.7.24, 0.7.23, 0.7.22, 0.7.21, 0.7.20, 0.7.17, 0.7.16, 0.7.15, 0.7.14, 0.7.13, 0.7.12, 0.7.11, 0.7.10, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.22, 0.5.21, 0.5.20, 0.5.18, 0.5.17, 0.5.16, 0.5.13, 0.5.12, 0.5.11, 0.5.10, 0.5.9, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.4.5, 0.4.4, 0.4.3, 0.4.0, 0.1.11, 0.1.10, 0.1.9, 0.1.7, 0.1.6, 0.1.4, 0.1.3, 0.1.2
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Downloads/js-framework-benchmark/inferno-v1.0.0-alpha7/npm-debug.log
child_process.js:529
    throw err;
    ^

Error: Command failed: npm install
    at checkExecSyncError (child_process.js:486:13)
    at execSync (child_process.js:526:13)
    at ~/Downloads/js-framework-benchmark/install.js:7:3
    at arrayEach (~/Downloads/js-framework-benchmark/node_modules/lodash/lodash.js:520:11)
    at Function.forEach (~/Downloads/js-framework-benchmark/node_modules/lodash/lodash.js:9202:14)
    at Object.<anonymous> (~/Downloads/js-framework-benchmark/install.js:5:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! js-framework-benchmark@1.0.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark@1.0.0 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Downloads/js-framework-benchmark/npm-debug.log
````

**Comment by krausest** [comment]
I love npm dependencies. Fixed in a6bdcae3f1b3a96e6fb0a1a29d6f0fc3c1a1ec9d.
