### ISSUE TITLE
npm build failure

### ISSUE THREAD

**Issue by hbfs** [krausest/js-framework-benchmark#58]
Thanks @krausest for the `npm install fix` with dependencies.. 
`npm install  81.69s user 12.57s system 106% cpu 1:28.52 total`

running into a build issue:

```
$ npm run build

> js-framework-benchmark@1.0.0 build ~/Downloads/js-framework-benchmark
> node build.js


> js-framework-benchmark-angular@1.0.0 build-prod ~/Downloads/js-framework-benchmark/angular-v1.5.8
> webpack -p -c webpack.config.js

Hash: 7c41281ac1dc4335b953
Version: webpack 1.13.2
Child
    Hash: 7c41281ac1dc4335b953
    Version: webpack 1.13.2
    Time: 5878ms
      Asset    Size  Chunks             Chunk Names
    main.js  250 kB       0  [emitted]  main
       [0] multi main 40 bytes {0} [built]
       [5] ./src/angularmin.js 75 bytes {0} [built]
       [6] ./webpack.config.js 525 bytes {0} [built]
        + 4 hidden modules

    WARNING in main.js from UglifyJs
    Side effects in initialization of unused variable jQuery [./src/main.es6.js:3,4]
    Condition always true [./~/jquery/dist/jquery.js:10035,0]

> angular2-webpack@1.0.0 build-prod ~/Downloads/js-framework-benchmark/angular-v2.0.0
> npm run precompile && node rollup.config.js --prod


> angular2-webpack@1.0.0 precompile ~/Downloads/js-framework-benchmark/angular-v2.0.0
> ngc

The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
closure compiler optimizing...
closure compiler optimizing complete
closure compiler optimizing...
closure compiler optimizing complete
built angular2

> js-framework-benchmark-aurelia@1.0.0 prebuild-prod ~/Downloads/js-framework-benchmark/aurelia-v1.0.0
> npm run clean:dist


> js-framework-benchmark-aurelia@1.0.0 clean:dist ~/Downloads/js-framework-benchmark/aurelia-v1.0.0
> rimraf dist


> js-framework-benchmark-aurelia@1.0.0 build-prod ~/Downloads/js-framework-benchmark/aurelia-v1.0.0
> cross-env NODE_ENV=production npm run webpack -- --progress --profile


> js-framework-benchmark-aurelia@1.0.0 webpack ~/Downloads/js-framework-benchmark/aurelia-v1.0.0
> cross-env ./node_modules/.bin/webpack "--progress" "--profile"

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'htmlLoader'. These properties are valid:
   object { amd?, bail?, cache?, context?, devServer?, devtool?, entry, externals?, loader?, module?, name?, dependencies?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
 - configuration.entry['app'] should be one of these:
   string | [string]
   The entry point for one output file.
 - configuration.entry should be one of these:
   object { <key>: string | [string] } | string | [string]
   The entry point(s) of the compilation.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { modules?, descriptionFiles?, plugins?, mainFields?, aliasFields?, mainFiles?, extensions?, enforceExtension?, moduleExtensions?, enforceModuleExtension?, alias?, symlinks?, unsafeCache?, cachePredicate?, fileSystem?, resolver? }

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run" "webpack" "--" "--progress" "--profile"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! js-framework-benchmark-aurelia@1.0.0 webpack: `cross-env ./node_modules/.bin/webpack "--progress" "--profile"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark-aurelia@1.0.0 webpack script 'cross-env ./node_modules/.bin/webpack "--progress" "--profile"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark-aurelia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env ./node_modules/.bin/webpack "--progress" "--profile"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark-aurelia
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark-aurelia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Downloads/js-framework-benchmark/aurelia-v1.0.0/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run" "build-prod"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! js-framework-benchmark-aurelia@1.0.0 build-prod: `cross-env NODE_ENV=production npm run webpack -- --progress --profile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark-aurelia@1.0.0 build-prod script 'cross-env NODE_ENV=production npm run webpack -- --progress --profile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark-aurelia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production npm run webpack -- --progress --profile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark-aurelia
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark-aurelia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Downloads/js-framework-benchmark/aurelia-v1.0.0/npm-debug.log
child_process.js:529
    throw err;
    ^

Error: Command failed: npm run build-prod
    at checkExecSyncError (child_process.js:486:13)
    at execSync (child_process.js:526:13)
    at ~/Downloads/js-framework-benchmark/build.js:7:3
    at arrayEach (~/Downloads/js-framework-benchmark/node_modules/lodash/lodash.js:520:11)
    at Function.forEach (~/Downloads/js-framework-benchmark/node_modules/lodash/lodash.js:9202:14)
    at Object.<anonymous> (~/Downloads/js-framework-benchmark/build.js:5:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! js-framework-benchmark@1.0.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark@1.0.0 build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-framework-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-framework-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-framework-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Downloads/js-framework-benchmark/npm-debug.log
```

**Comment by krausest** [comment]
As of 9f059b8e7de77bc55f94f4181460fea072be57c4 I hope to have fixed the aurelia build. I just cloned and rebuilt on my linux vm and it seems to work there (for that second).

**Comment by hbfs** [comment]
Thanks! got it building and running on OS X - it crashed during the selenium tests 2x. Not sure if its because my monitor went to sleep or because I switched desktops, but probably GUI related.
