### ISSUE TITLE
URL is not defined

### ISSUE THREAD

**Issue by mindplay-dk** [krausest/js-framework-benchmark#651]
I followed the instructions in step 4 of the README to get the automated benchmark driver running, and everything installed without errors.

I've successfully built and run the `keyed/preact` benchmark via the web-server.

I then tried to run the benchmark under the `webdriver-ts`, and it fails:

```
$ npm run bench keyed/preact

> webdriver-ts@1.0.0 bench /mnt/c/workspace/js-framework-benchmark/webdriver-ts
> cross-env LANG="en_US.UTF-8" node dist/benchmarkRunner.js "keyed/preact"

/mnt/c/workspace/js-framework-benchmark/webdriver-ts/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:35
class URLShim extends URL {
                      ^

ReferenceError: URL is not defined
    at Object.<anonymous> (/mnt/c/workspace/js-framework-benchmark/webdriver-ts/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:35:23)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/mnt/c/workspace/js-framework-benchmark/webdriver-ts/node_modules/lighthouse/lighthouse-core/lib/network-request.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```

Looks like a similar problem was reported and fixed earlier in #593.

But it looks like we're still missing a `URL` polyfill for node or something?

**Comment by krausest** [comment]
Sorry, seems like I should update the README and require at least node 10.

**Comment by krausest** [comment]
README is updated. Can you try with the current LTS (10.16.3)?

**Comment by mindplay-dk** [comment]
Okay, so now it starts, but just goes into endless errors and retries... 🤷‍♂️

```
$ npm run bench keyed/react-hooks

> webdriver-ts@1.0.0 bench /mnt/c/workspace/js-framework-benchmark/webdriver-ts
> cross-env LANG="en_US.UTF-8" node dist/benchmarkRunner.js "keyed/react-hooks"

MODE: Directory names. Using arguments as the directory names to be re-run:  [ 'keyed/react-hooks' ]
http://localhost:8080/frameworks/keyed/react-hooks/package-lock.json
{ _:
   [ '/usr/bin/node',
     '/mnt/c/workspace/js-framework-benchmark/webdriver-ts/dist/benchmarkRunner.js',
     'keyed/react-hooks' ],
  check: 'false',
  fork: 'true',
  exitOnError: 'false',
  'exit-on-error': 'false',
  count: 9007199254740991,
  port: 8080,
  '$0': 'dist/benchmarkRunner.js' } 'no-results' undefined true
fork chromedriver process? true
Frameworks that will be benchmarked [ 'react-hooks-v16.8.6-keyed' ]
Benchmarks that will be run [ '01_run1k',
  '02_replace1k',
  '03_update10th1k_x16',
  '04_select1k',
  '05_swap1k',
  '06_remove-one-1k',
  '07_create10k',
  '08_create1k-after1k_x2',
  '09_clear1k_x8',
  '21_ready-memory',
  '22_run-memory',
  '23_update5-memory',
  '24_run5-memory',
  '25_run-clear-memory',
  '30_startup' ]
Executing benchmark react-hooks and benchmark 01_run1k retry # 1
START BENCHMARK. Write results?  true
benchmarking  { name: 'react-hooks',
  fullNameWithKeyedAndVersion: 'react-hooks-v16.8.6-keyed',
  uri: 'frameworks/keyed/react-hooks',
  keyed: true,
  useShadowRoot: false } 01_run1k
chromedriver: 4.716ms before setUseShadowRoot
chromedriver: 5.542ms before get
(node:15938) Warning: No such label 'chromedriver' for console.timeLog()
ERROR in run Benchmark: | Error: Server terminated early with status 127
    at earlyTermination.catch.e (/mnt/c/workspace/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/remote/index.js:251:52)
    at process._tickCallback (internal/process/next_tick.js:68:7) | type: object  instance of Error true  Message:  Server terminated early with status 127
Error is instanceof Error
ERROR cleaning up driver Error: Server terminated early with status 127
    at earlyTermination.catch.e (/mnt/c/workspace/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/remote/index.js:251:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
******* STRANGE selenium error found - retry
Executing benchmark react-hooks and benchmark 01_run1k retry # 2
START BENCHMARK. Write results?  true
benchmarking  { name: 'react-hooks',
  fullNameWithKeyedAndVersion: 'react-hooks-v16.8.6-keyed',
  uri: 'frameworks/keyed/react-hooks',
  keyed: true,
  useShadowRoot: false } 01_run1k
chromedriver: 5.213ms before setUseShadowRoot
chromedriver: 5.753ms before get
(node:15946) Warning: No such label 'chromedriver' for console.timeLog()
ERROR in run Benchmark: | Error: Server terminated early with status 127
    at earlyTermination.catch.e (/mnt/c/workspace/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/remote/index.js:251:52)
    at process._tickCallback (internal/process/next_tick.js:68:7) | type: object  instance of Error true  Message:  Server terminated early with status 127
Error is instanceof Error
ERROR cleaning up driver Error: Server terminated early with status 127
    at earlyTermination.catch.e (/mnt/c/workspace/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/remote/index.js:251:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
******* STRANGE selenium error found - retry
```

It goes on like that for a while...

Is there something else missing in the README? Something else I need to install?

**Comment by krausest** [comment]
I'm afraid not. Basically it looks good. The benchmark driver starts and finds the correct framework and benchmark. But then chromedriver reports that "the server terminated early". 
I've seen such an error before under rare circumstances on linux (but it was status 1 https://github.com/krausest/js-framework-benchmark/issues/622#issuecomment-527624673) , but it seems like it happens all the time on your machine.

What's your setup? 

If you're running on WSL you may build and serve the implementations on the WSL side, but the chromedriver must be installed and run from windows (i.e. webdriver-ts must be installed and run from the windows side).
The simplest option should be building and running on windows (this worked for most frameworks #546 , though some refuse to build on windows). .

**Comment by krausest** [comment]
To avoid further frustrations I booted windows and checked that if you follow along the README building react-hooks works (on my machine) on Windows, cmd as terminal and node v10.16.0.

**Comment by mindplay-dk** [comment]
Man, WSL is nothing but trouble. 😑

I have to get myself a proper Linux installation one of these days.

**Comment by krausest** [comment]
An alternative would be to try the docker build as [explained](https://github.com/krausest/js-framework-benchmark/wiki/Build-all-frameworks-with-docker)in  the wiki. I tested it since yesterday on windows. It worked fine on my machine, but it takes literally days to run all benchmarks. After 14 hours all keyed implementations were done.
If you decide to give it a shot please tell me about your experience with it.

**Comment by krausest** [comment]
Closing it - since last test on windows looked "good" (not including the delay...)
