### ISSUE TITLE
Warning: No such label 'chromedriver' for console.timeLog()

### ISSUE THREAD

**Issue by eyeinsky** [krausest/js-framework-benchmark#712]
Thanks for the previous help, just going forward with trying to get this working. :)

So now instead of trying to look at the browser console I tried to run the webdriver test for keyed vanillajs and get this warning:
 `(node:24097) Warning: No such label 'chromedriver' for console.timeLog()`.

I'm not familiar with timeLog, but it looks to me that the label `"chromedriver"` isn't set.

Running the webdriver probably works for other people, but just not for me, so how could I debug this?

```
> webdriver-ts@1.0.0 bench /home/user/src/js-framework-benchmark/webdriver-ts
> cross-env LANG="en_US.UTF-8" node dist/benchmarkRunner.js "keyed/vanillajs"

MODE: Directory names. Using arguments as the directory names to be re-run:  [ 'keyed/vanillajs' ]
{ _:
   [ '/nix/store/2rbbn30ii3xi5aa9rdlgsw5xfk634wfg-nodejs-10.17.0/bin/node',
     '/home/user/src/js-framework-benchmark/webdriver-ts/dist/benchmarkRunner.js',
     'keyed/vanillajs' ],
  check: 'false',
  fork: 'true',
  exitOnError: 'false',
  'exit-on-error': 'false',
  count: 9007199254740991,
  port: 8080,
  '$0': 'dist/benchmarkRunner.js' } 'no-results' undefined true
fork chromedriver process? true
Frameworks that will be benchmarked [ 'vanillajs-keyed' ]
Benchmarks that will be run [ '01_run1k',
  '02_replace1k',
  '03_update10th1k_x16',
  '04_select1k',
  '05_swap1k',
  '06_remove-one-1k',
  '07_create10k',
  '08_create1k-after1k_x2',
  '09_clear1k_x8',
  '21_ready-memory',
  '22_run-memory',
  '23_update5-memory',
  '24_run5-memory',
  '25_run-clear-memory',
  '30_startup' ]
Executing benchmark vanillajs and benchmark 01_run1k retry # 1
START BENCHMARK. Write results?  true
benchmarking  { name: 'vanillajs',
  fullNameWithKeyedAndVersion: 'vanillajs-keyed',
  uri: 'frameworks/keyed/vanillajs',
  keyed: true,
  useShadowRoot: false } 01_run1k
chromedriver: 2.136ms before setUseShadowRoot
chromedriver: 2.249ms before get
(node:24097) Warning: No such label 'chromedriver' for console.timeLog()
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/user/src/js-framework-benchmark/webdriver-ts/node_modules/chromedriver/lib/chromedriver/chromedriver ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by fabiospampinato** [comment]
Check that ports 9998 and 9999 are unused (or set other ports).

**Comment by krausest** [comment]
I just noticed that the warning is no longer printed (but is wasn't causing an error).
