### ISSUE TITLE
Elm build stopped working

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#746]
The elm build causes the following error:
```
*** Executing npm install in frameworks/keyed/elm

> elm@0.19.0-bugfix2 install /build/frameworks/keyed/elm/node_modules/elm
> binwrap-install

fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (/build/frameworks/keyed/elm/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/build/frameworks/keyed/elm/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/build/frameworks/keyed/elm/node_modules/unzip/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.0-bugfix2 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm@0.19.0-bugfix2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-04T17_21_14_757Z-debug.log
child_process.js:650
    throw err;
    ^
```

**Comment by krausest** [comment]
Seems to be due to updating node. Looks like updating to elm 0.19.1-3 helps.

**Comment by krausest** [comment]
Works with that update again!
