### ISSUE TITLE
Headless Installation

### ISSUE THREAD

**Issue by docgonzo2015** [krausest/js-framework-benchmark#931]
Hi!
I've tried to start the benchmark, but i've got on a headless server a failure:

` npm run check keyed/angular

> webdriver-ts@1.0.0 check
> cross-env LANG="en_US.UTF-8" node dist/isKeyed.js "keyed/angular"
args.framework undefined true
http://localhost:8080/frameworks/keyed/angular/package-lock.json
Frameworks that will be checked angular-v12.0.1-keyed
ERROR running angular-v12.0.1-keyed WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/home/deploy/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/home/deploy/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:642:13)
    at Executor.execute (/home/deploy/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:568:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  remoteStacktrace: '#0 0x564d90729949 <unknown>\n'
}
error calling driver.quit - ignoring this exception`

Any Ideas?

**Comment by krausest** [comment]
`npm run bench -- --headless` and `npm run isKeyed -- --headless` should do the trick. Does that work for you?
